apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: sonmt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: maithanhson/demo-k8s:category-app
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: jdbc:mysql://mysql:3306/your_database_name  # Replace with your database name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
